### PR TITLE
Run CI for code changes in PR/master

### PR DESCRIPTION
**Pull request by tomkerkhove**
Run CI for code changes in PR/master:
- Trigger for changes in `master` branch when `src/*` has changed
- Trigger for PR with changes in `src/*`

### CODE REVIEW

**Comment by tomkerkhove** [comment]
If these work as they should, would you mind making the same changes on the other projects please @stijnmoreels 	?

**Comment by stijnmoreels** [comment]
> If these work as they should, would you mind making the same changes on the other projects please @stijnmoreels ?

Yep, will you let me know when I can make these changes?

**Comment by tomkerkhove** [comment]
Let's just do it, it should be ok.

**Pull request merged**
