### PR TITLE
DOC: update README.md with YAML build

### PR DESCRIPTION
**Pull request by stijnmoreels**
Relates to #35

### CODE REVIEW

**Comment by tomkerkhove** [comment]
I was actually wondering about this, we might need to change our [trigger](https://github.com/arcus-azure/arcus.eventgrid.proxy/blob/master/build/ci-build.yml#L3) to `master`, otherwise the badge will never be updated.

Thoughts?

**Comment by tomkerkhove** [comment]
Also, we might want to change the `trigger` & `pr` to only run when something changed in `/src`?

**Comment by stijnmoreels** [comment]
> I was actually wondering about this, we might need to change our [trigger](https://github.com/arcus-azure/arcus.eventgrid.proxy/blob/master/build/ci-build.yml#L3) to `master`, otherwise the badge will never be updated.
> 
> Thoughts?

Hmm, the url to the build definition got `/latest` in the path; so I would guess that it always shows the most recent one?

**Comment by tomkerkhove** [comment]
Yes - but it is limited to `master` branch, which is how it should be, but it will never build master branch as it only builds PRs for now.

Hence why I'm requestioning things, but moving this to https://github.com/arcus-azure/arcus.eventgrid.proxy/pull/39

**Pull request merged**
